- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: myResourceGroup
      location: eastus
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: myResourceGroup
      name: myVnet
      address_prefixes: "10.0.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: myResourceGroup
      name: webSubnet
      address_prefix: "10.0.1.0/24"
      virtual_network: myVnet
  - name: Add subnet
    azure_rm_subnet:
      resource_group: myResourceGroup
      name: dbSubnet
      address_prefix: "10.0.2.0/24"
      virtual_network: myVnet
  - name: Create Network Security Group that allows SSH
    azure_rm_securitygroup:
      resource_group: myResourceGroup
      name: myNetworkSecurityGroup
      rules:
        - name: SSH
          protocol: Tcp
          destination_port_range: 1329
          access: Allow
          priority: 1001
          direction: Outbound
