- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: Create resource group
    azure_rm_resourcegroup:
      name: app-vNet-rg
      location: eastus
  - name: Create virtual network
    azure_rm_virtualnetwork:
      resource_group: app-vNet-rg
      name: app-eus-vNet
      address_prefixes: "10.10.0.0/16"
  - name: Add subnet
    azure_rm_subnet:
      resource_group: app-vNet-rg
      name: Frontend
      address_prefix: "10.10.2.0/24"
      virtual_network: app-eus-vNet
  - name: Add subnet
    azure_rm_subnet:
      resource_group: app-vNet-rg
      name: Backend
      address_prefix: "10.10.4.0/24"
      virtual_network: app-eus-vNet
  - name: Add subnet
    azure_rm_subnet:
      resource_group: app-vNet-rg
      name: Midtier
      address_prefix: "10.10.5.0/24"
      virtual_network: app-eus-vNet


      
      