---
- name: new connection
 # connection: local
- hosts: 
     linuxservers
  become: yes
  tasks:
  - name: Install packages
    apt:
      name:
      - nginx
      state: latest
      cache_valid_time: 3600
