- name: Create Azure VM
  hosts: localhost
  connection: local
  tasks:
  - name: create an account
    azure_rm_storageaccount:
      resource_group: app-vNet-rg
      name: clh00029909
      type: Standard_RAGRS
      tags:
        testing: testing
        delete: on-exit